### ISSUE TITLE
Message #16 - Negation

### ISSUE THREAD

**Issue by gringer** [zaitsev85/message-from-space#23]
Operator :10 (*neg*) converts from negative to positive, and vice versa.

**Comment by mx00s** [comment]
I noticed you opened #22 to start improving the docs. Should that be reopened?

**Comment by gringer** [comment]
You mentioned on Discord that it's a better idea to have a single issue per message. I think that's a reasonable idea:

> things are going to get lost/repeated here unnecessarily, and filing an PR will take time. Instead, let's open an issue corresponding to each message and track ideas about each there.

https://discord.com/channels/728323267039068221/728323622757728417/733671978552000594

Oh... but Ivan wants the discussions only on Discord. That seems... not very productive.

**Comment by mx00s** [comment]
Great, don't hesitate to file a PR too if you're pretty sure you know what we need to do.
