### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by mx00s** [zaitsev85/message-from-space#44]
We need to maintain a table of the decided names for each generic symbol.

| Name  | Generic Symbol | Messages | `annotate.hs` updated? |
| ------------- | ------------- | ------------- | ------------- |
| `t` | `:2` | 11, 21 | yes |
| `f` | `:8` | 11, 22 | yes |
| `ap` | `:0` | 5, 17 | yes |
| `send` | `:174` | 15 | #43 |
| `neg` | `:10` | 16 | #43 |
| `s` | `:7` | 18 | #43 |
| `c` | `:6` | 19 | #43 |
| `b` | `:5` | 20 | #43 |
| `pwr2` | `:68191693600` | 23 | #43 |
| `i` | new glyph | 24 | no |
| `cons` | `:64170` | 25 | #43 |
| `car` | `:64174` | 26 | #43 |
| `cdr` | `:64171` | 27 | #43  |
| `nil` | `:14` | 28 | #43 |
| `isnil` | new glyph | 29 | no |
| `( _ , _ )` | pictoral glyphs for `(`, `,`, and `)` | 30 | no |
| `vec` | `:17043521` | 31 | no |
| `chkb` | `:11184810` | 33 | no |
| `if0` | `:58336` | 37 | #43 |

**Comment by zaitsev85** [comment]
We have all the names in place now, thanks a lot!
