### ISSUE TITLE
Message #32 - Plotting

### ISSUE THREAD

**Issue by gringer** [zaitsev85/message-from-space#46]
The application of the square symbol to an arrow-enclosed sequence of plot commands results in an image being displayed.

Line 1: do nothing (plot command list is empty)
Line 2: the plot command takes two arguments. When these arguments are both 1, display a single dot one pixel in (in both directions) from the top left of the screen.
Line 3: the last argument describes vertical displacement. When the first argument is 1, and the second argument is 2, display a single dot two pixels down and one across from the top left of the screen.
Line 4: demonstrates a pixel at (2 across, 5 down)
Line 5: multiple plotting commands are separated by a bar. This puts one pixel at (1, 2) and one at (3, 1)
Line 6: this is a plotting command sequence that displays five pixels in a shape representing the grid number 2.

**Comment by zaitsev85** [comment]
That's not exactly multiple commands separated by a bar. It's just a list of points. But I get the general idea, thanks!
